apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/instance: nightwatcher
  name: nightwatcher
  namespace: gaia-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nightwatcher
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: nightwatcher
    spec:
      containers:
      - image: lmxia/nightwatcher:v1.0.2
        imagePullPolicy: Always
        name: app
        ports:
        - containerPort: 8282
          name: api
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /api/v1/health_check
            port: api
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 500m
            memory: 1024Mi
          requests:
            cpu: 100m
            memory: 128Mi
      serviceAccountName: nightwatcher