---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gaia:nightwatcher
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: nightwatcher
    namespace: gaia-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: nightwatcher
  namespace: gaia-system
