---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: gaia:bin
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cluster-admin
subjects:
  - kind: ServiceAccount
    name: bin
    namespace: gaia-system

---
kind: ServiceAccount
apiVersion: v1
metadata:
  name: bin
  namespace: gaia-system
