apiVersion: v1
kind: Service
metadata:
  name: nightwatcher
  namespace: gaia-system
spec:
  ports:
  - name: http
    port: 8282
    protocol: TCP
    targetPort: 8282
  selector:
    app.kubernetes.io/instance: nightwatcher
  type: ClusterIP