apiVersion: v1
kind: Service
metadata:
  name: k8s-api-service
  namespace: dev
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: api
  selector:
    app.kubernetes.io/instance: k8s-api-service
  # type: LoadBalancer
  type: ClusterIP